### ISSUE TITLE
Is this bannable?

### ISSUE THREAD

**Issue by croboy** [Project-Diablo-2/BH#31]
Your Filter update is exactly what I've wanted PD2 to release.

I want to use it, but is it safe?

**Comment by WolfieeifloW** [comment]
I may be midunderstanding, but filters are perfectly fine to use in PD2. Just choose one from the launcher or put your own into the `loot.filter` file.

**Comment by croboy** [comment]
I saw something that says you can filter the game list?

I want to be able to use the lobby filter to filter only hell games. Can this filter game lists

**Comment by fergushev** [comment]
I assume you're talking about [this](https://github.com/Project-Diablo-2/BH/pull/29)?
No, you'll have to wait until it gets implemented/merged.

**Comment by croboy** [comment]
When will that be? Really cool feature for pd2
